start: clauses+

?clauses: acl__start
        | controls__start
        | include__start
        | key__start
        | logging__start
        | dscpsocketlist__start
        | options

%import .acl.start -> acl__start
%import .controls.start -> controls__start
%import .include.start -> include__start
%import .key.start -> key__start
%import .logging.start -> logging__start
%import .dscpsocketlist.start -> dscpsocketlist__start
%import .options.start -> options
%import common.WS
%ignore WS
