// for alt-transfer-source, notify-source, parental-source, transfer-source statements

start: clause_type ip_addr (port)? (dscp)? ";"

clause_type: CLAUSE_TYPE
ip_addr: IPV6_ADDR | WILDCARD
port: "port" ( UINT16 | WILDCARD )
dscp: "dscp" DSCP

CLAUSE_TYPE: "alt-transfer-source-v6" | "notify-source-v6" | "parental-source-v6" | "transfer-source-v6"

%import .isc_terminals (QUOTED_STRING, DSCP, UINT16, IPV6_ADDR, WILDCARD)
%import common.WS
%ignore WS